In [3]:
import numpy as np
from matplotlib import pyplot as plt

In [4]:
A = np.array([[0.5, 0.5, 0.24],
              [0.25, 0.0, 0.25],
              [0.25, 0.5, 0.5]])

In [6]:
print(A)

[[0.5  0.5  0.24]
 [0.25 0.   0.25]
 [0.25 0.5  0.5 ]]


In [5]:
x_today = np.array([[1], 
                    [0],
                    [0]])

In [7]:
for k in range(50):
    x_tomorrow = A@x_today
    print(k)
    print(x_tomorrow)
    x_today = x_tomorrow

0
[[0.5 ]
 [0.25]
 [0.25]]
1
[[0.435 ]
 [0.1875]
 [0.375 ]]
2
[[0.40125]
 [0.2025 ]
 [0.39   ]]
3
[[0.395475 ]
 [0.1978125]
 [0.3965625]]
4
[[0.39181875]
 [0.19800938]
 [0.39605625]]
5
[[0.38996756]
 [0.19696875]
 [0.3949875 ]]
6
[[0.38826516]
 [0.19623877]
 [0.39347002]]
7
[[0.38668476]
 [0.19543379]
 [0.39192068]]
8
[[0.38512024]
 [0.19465136]
 [0.39034843]]
9
[[0.38356942]
 [0.19386717]
 [0.38877995]]
10
[[0.38202548]
 [0.19308734]
 [0.38721592]]
11
[[0.38048823]
 [0.19231035]
 [0.385658  ]]
12
[[0.37895721]
 [0.19153656]
 [0.38410624]]
13
[[0.37743238]
 [0.19076586]
 [0.3825607 ]]
14
[[0.37591369]
 [0.18999827]
 [0.38102138]]
15
[[0.37440111]
 [0.18923377]
 [0.37948825]]
16
[[0.37289462]
 [0.18847234]
 [0.37796128]]
17
[[0.37139419]
 [0.18771398]
 [0.37644047]]
18
[[0.36989979]
 [0.18695866]
 [0.37492577]]
19
[[0.36841141]
 [0.18620639]
 [0.37341716]]
20
[[0.36692902]
 [0.18545714]
 [0.37191463]]
21
[[0.36545259]
 [0.18471091]
 [0.37041814]]
22
[[0.36398211]
 [0.18396768]
 [0.36892